#!/bin/bash
sudo apt-get update -y
sudo apt-get install nginx -y
sudo apt-get install python3-flask -y
sudo apt-get install mysql-server -y
sudo apt-get install python3-mysql.connector -y
sudo apt-get install vim-python-jedi -y
sudo apt-get install uwsgi -y
sudo apt-get install uwsgi-plugin-python3 -y
sudo apt-get install geany -y
#pip3 install --user Flask-WTF -y
sudo pip3 install Flask-WTF -y
